### PR TITLE
Render Cio HTTPS requests

### PR DESCRIPTION
**Pull request by crgee1**
Providing a standard search or browse https request to the search bar will return those results for easier visual review

### CODE REVIEW

**Review by jjl014 — COMMENTED** [review]
@crgee1 This is super cool. Nicely done!

I noticed that the `i` and `s` params from the request URL that you paste doesn't overwrite the current ones from the browser. Not necessary, but it would be cool if we can pass those along!

Separately, this is an example repo so I don't think we want to introduce any additional complexities that could be confusing to people who might be referencing it. Would it be possible to abstract all of this logic to a helper function and add comments? Or would it make more sense to move this to the demo repo?

Let me know what you think. Thanks!

**Comment by crgee1** [comment]
> 

I'm not a fan of the demo repo for multiple reasons. It's password protected, I don't like the framework, it doesn't have sort so I'm preferable to making helper functions

**Review by jjl014 — COMMENTED** [review]
Thanks for the updates!

Looking at this a bit more, I don't think pulling the logic out into separate functions make sense. I didn't realize this was already a utils file so I think we'll want to revert the change and just add comments around the original conditional logic we had in place. I think it would be cleaner.

As for the comment, what do you think about rephrasing the comment to be something along the lines of:

`Custom functionality - allows usage of cnstrc request urls in the search bar`

**Review by jjl014 — APPROVED** [review]
Nice, this looks great to me! Thanks for making the adjustment and sorry for not getting back to you sooner!

One last thing would be to add in support for the `ui` parameter. Other than that. feel free to merge afterwards! 🚀

**Pull request merged**
