### PR TITLE
[CSL-1371] made react example mobile responsive

### PR DESCRIPTION
**Pull request by Here2Huynh**
added classes to make components mobile responsive
 
 thanks @mocca102 for the help!

### CODE REVIEW

**Review by jjl014 — COMMENTED** [review]
Nice work! This is looking pretty sweet to me. A couple comments/questions:

* What do you think about centering the logo in the mobile view?
* The spacing on the left/right sides of the search bar is a little uneven, let's try to center it a bit more and take up the full width w/ some margin/padding
* We should probably add a border around the sorting option dropdown to make it a little more noticeable
    * Maybe we can have the filter button and the sort dropdown button on the same row and add a "Filter" label next to the filter icon
* Should we add an `X` button to the filters modal?
* We might want to make the text slightly larger on the result cards and filters for mobile so it's easier to read/interact with

Other than that, it's looking pretty good! Let me know what you think. :)

**Comment by Here2Huynh** [comment]
> Nice work! This is looking pretty sweet to me. A couple comments/questions:
> 
> * What do you think about centering the logo in the mobile view?
> * The spacing on the left/right sides of the search bar is a little uneven, let's try to center it a bit more and take up the full width w/ some margin/padding
> * We should probably add a border around the sorting option dropdown to make it a little more noticeable
>   
>   * Maybe we can have the filter button and the sort dropdown button on the same row and add a "Filter" label next to the filter icon
> * Should we add an `X` button to the filters modal?
> * We might want to make the text slightly larger on the result cards and filters for mobile so it's easier to read/interact with
> 
> Other than that, it's looking pretty good! Let me know what you think. :)



> Nice work! This is looking pretty sweet to me. A couple comments/questions:
> 
> * What do you think about centering the logo in the mobile view?
> * The spacing on the left/right sides of the search bar is a little uneven, let's try to center it a bit more and take up the full width w/ some margin/padding
> * We should probably add a border around the sorting option dropdown to make it a little more noticeable
>   
>   * Maybe we can have the filter button and the sort dropdown button on the same row and add a "Filter" label next to the filter icon
> * Should we add an `X` button to the filters modal?
> * We might want to make the text slightly larger on the result cards and filters for mobile so it's easier to read/interact with
> 
> Other than that, it's looking pretty good! Let me know what you think. :)


All good ideas, added them in!

**Comment by jjl014** [comment]
* Made some minor updates to some of the classes used
* Restricted scrolling on body when modal is open

**Comment by jjl014** [comment]
@Constructor-io/customer-integrations Could you guys review this PR when you get a chance? Thanks!

**Review by esezen — APPROVED** [review]
LGTM!

**Pull request merged**
